repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.13
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy src/
        language: system
        pass_filenames: false
        always_run: true

      - id: pytest
        name: pytest (tests + import check)
        entry: poetry run pytest --doctest-modules src/ tests/
        language: system
        pass_filenames: false
        always_run: true
